### ISSUE TITLE
Component library (probably material)

### ISSUE THREAD

**Issue by egu3334** [jd-116/project-management#24]
![Annotation 2020-08-23 234648.png](https://images.zenhubusercontent.com/5c36a78eb7d8a251f243c2aa/a2904352-ea9c-4c01-9b12-cb73abf419cd)

**Comment by Twinov** [comment]
We're going to be using [Native Base](https://github.com/GeekyAnts/NativeBase) because I saw it on a tutorial and it had a great introductory gif.
